# Generated by Django 4.0.1 on 2023-04-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
