# Generated by Django 4.0.1 on 2023-04-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0002_remove_friend_profile_delete_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
